version: '3.8'
networks:
    asma:
        name: asma

services:
    asma-srv-synchronizator:
        container_name: asma-srv-synchronizator
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '9100:9100'
        restart: unless-stopped
        environment:
            NODE_ENV: development
            DEBUG_MODE: 'true'
            PORT: ${PORT}
            DEVELOPMENT: 'true'
            API_KEY: ${API_KEY}
            API_URL: ${API_URL_NONPROD}
            JWT_SECRET: ${JWT_SECRET}
        networks:
            - asma
