FROM alpine

WORKDIR /auth_dir

COPY package.json .

COPY yarn.lock .

COPY . .

RUN  apk --no-cache add --update bash \
	&& apk add yarn \
	&& apk add npm \
	#/&& curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
	#&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
	&& yarn install \
	&& apk update
	#&& apt install yarn -y

CMD yarn nodemon