variables:
    serviceName: asma-srv-synchronizator

resources:
    repositories:
        - repository: templates
          type: git
          name: Arbeidoginkludering/asma-infrastructure
          ref: refs/heads/master

trigger:
    branches:
        include:
            - master

pr: none

name: $(Build.SourceBranchName)_$(Build.SourceVersion)
stages:
    - stage: Docker_build_and_push
      jobs:
          - template: pipelineTemplates/dockerBuildPushNode.yaml@templates
            parameters:
                serviceName: ${{ variables.serviceName }}

    - stage: Create_artifact
      variables:
          - group: common-vg
      jobs:
          - template: pipelineTemplates/createArtifact.yaml@templates
            parameters:
                serviceName: ${{ variables.serviceName }}
